name: The Daily Liar Network
favicon: null
layout_spectrum: 0.99638
typography_spectrum: 0.90728
title: The Daily Liar Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-61078204-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d19'
    - '#970609'
    - '#c6c6c6'
    - '#5c3c31'
    - '#998a87'
  brandStrength: 0
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
