name: The Daily Liar Network
favicon: null
layout_spectrum: 0.49423685390502214
typography_spectrum: 0.22109533031471074
title: The Daily Liar Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-61078204-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.016607054974883795
  lightness: 0.4220057241618633
  saturation: 0.15710071730427444
  rhythmicContrast: 0.6092305204365402
purpose: []
