name: The Daily Liar Network
favicon: null
layout_spectrum: 0.99638
typography_spectrum: 0.90728
title: The Daily Liar Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-61078204-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ca0000'
    - '#df464b'
    - '#5f5c5d'
    - '#f6dfe2'
  brandStrength: 0
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
